# Generated by Django 4.1.2 on 2022-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='room',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
